<?php
return [
    [
        'icon'=>'glyphicon-envelope',
        'name'=>'Email',
        'url'=>'#',
    ],
    [
        'icon'=>'glyphicon-user',
        'name'=>'User',
        'url'=>'#',
    ],
    [
        'icon'=>'glyphicon-camera',
        'name'=>'Camera',
        'url'=>'#',
    ],
    [
        'icon'=>'glyphicon-phone',
        'name'=>'Phone',
        'url'=>'#',
    ],
    [
        'icon'=>'glyphicon-qrcode',
        'name'=>'二维码',
        'url'=>'#',
    ],
    [
        'icon'=>'glyphicon-map-marker',
        'name'=>'地图',
        'url'=>'#',
    ],
    [
        'icon'=>'glyphicon-cog',
        'name'=>'设置',
        'url'=>'#',
    ],
];