<?php
return [
    [
        'icon'=>'glyphicon-envelope',
        'name'=>'Email',
        'toUrl'=>'',
    ],
    [
        'icon'=>'glyphicon-user',
        'name'=>'User',
        'toUrl'=>'',
    ],
    [
        'icon'=>'glyphicon-camera',
        'name'=>'Camera',
        'toUrl'=>'',
    ],
    [
        'icon'=>'glyphicon-phone',
        'name'=>'Phone',
        'totoUrl'=>'',
        'url'=>'tel:13141234768',
        'id'=>'tell-me'
    ],
    [
        'icon'=>'glyphicon-qrcode',
        'name'=>'二维码',
        'toUrl'=>'',
        'url'=>'javascript:void(0)',
        'id'=>'qr-code'
    ],
    [
        'icon'=>'glyphicon-map-marker',
        'name'=>'地图',
        'toUrl'=>'',
    ],
    [
        'icon'=>'glyphicon-cog',
        'name'=>'设置',
        'toUrl'=>'',
    ],
];