<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "ml_lucky".
 *
 * @property integer $id
 * @property string $username
 * @property integer $phone
 * @property integer $winning
 * @property integer $date
 * @property integer $addtime
 */
class MlLucky extends \yii\db\ActiveRecord
{
    public function beforeSave($insert)
    {
        if($this->isNewRecord) {
            $this->date = strtotime(date('Y-m-d'));
            $this->addtime = time();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ml_lucky';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['username','phone'], 'required', 'message'=>'{attribute}不能为空.'],
            [[ 'winning', 'date', 'addtime'], 'integer'],
            ['phone','unique','message'=>'您输入的{attribute}已参与过此次抽奖.'],
            ['phone','match','pattern'=>'/^13[0-9]{9}$|15[0-9]{9}$|18[0-9]{9}$|14[579][0-9]{8}$|17[013678][0-9]{8}$/','message'=>'{attribute}输入有误,请输入正确的{attribute}.'],

            [['username'],'match','pattern'=>'/^[\x{4e00}-\x{9fa5}]+$/u','message'=>'{attribute}必需为汉字.'],
            [['username'],'string', 'max' => 4, 'min'=>2,'tooShort'=>'{attribute}应为2-4个汉字.','tooLong'=>'{attribute}应为2-4个汉字.'],
            [['winning'], 'default','value'=>0]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'username' => '姓名',
            'phone' => '手机号',
            'winning' => '是否中奖',
            'date' => '日期',
            'addtime' => '参与时间',
        ];
    }
}
